[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor --chip esp32s3"
rustflags = [
  # esp-hal provides startup code; do not link the GCC startup files.
  "-C", "link-arg=-nostartfiles",
]

[env]
ESP_LOG="info"

[build]
target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["alloc", "core"]
